function aa(a){return function(){return this[a]}}var g,j=this;function ba(){}
function ca(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(!(a instanceof Object)&&(Object.prototype.toString.call(a)=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call")))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function da(a){return ca(a)=="array"}function ea(a){var b=ca(a);return b=="array"||b=="object"&&typeof a.length=="number"}function o(a){return typeof a=="string"}function p(a){return typeof a=="number"}function fa(a){return ca(a)=="function"}function ga(a){a=ca(a);return a=="object"||a=="array"||a=="function"}function ha(a){if(a.hasOwnProperty&&a.hasOwnProperty(ia))return a[ia];a[ia]||(a[ia]=++ja);return a[ia]}
var ia="closure_hashCode_"+Math.floor(Math.random()*2147483648).toString(36),ja=0;function ka(a){var b=ca(a);if(b=="object"||b=="array"){if(a.S)return a.S.call(a);b=b=="array"?[]:{};for(var c in a)b[c]=ka(a[c]);return b}return a}function la(a,b){var c=b||j;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(c,e)}}else return function(){return a.apply(c,arguments)}}
var ma=Date.now||function(){return+new Date};function q(a,b){function c(){}c.prototype=b.prototype;a.g=b.prototype;a.prototype=new c;a.prototype.constructor=a};var s=Array.prototype,na=s.indexOf?function(a,b,c){return s.indexOf.call(a,b,c)}:function(a,b,c){c=c==null?0:c<0?Math.max(0,a.length+c):c;if(o(a)){if(!o(b)||b.length!=1)return-1;return a.indexOf(b,c)}for(c=c;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},oa=s.forEach?function(a,b,c){s.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=o(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};function pa(a,b){var c=na(a,b),d;if(d=c>=0)s.splice.call(a,c,1);return d}
function qa(){return s.concat.apply(s,arguments)}function ra(a){if(da(a))return qa(a);else{for(var b=[],c=0,d=a.length;c<d;c++)b[c]=a[c];return b}};var sa;function t(a,b){this.width=a;this.height=b}g=t.prototype;g.S=function(){return new t(this.width,this.height)};g.toString=function(){return"("+this.width+" x "+this.height+")"};g.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};g.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};g.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
g.scale=function(a){this.width*=a;this.height*=a;return this};function ta(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function ua(a,b){var c;if(c=b in a)delete a[b];return c}var va=["constructor","hasOwnProperty","isPrototypeOf","propertyIsEnumerable","toLocaleString","toString","valueOf"];function wa(a){for(var b,c,d=1;d<arguments.length;d++){c=arguments[d];for(b in c)a[b]=c[b];for(var e=0;e<va.length;e++){b=va[e];if(Object.prototype.hasOwnProperty.call(c,b))a[b]=c[b]}}};function xa(a,b){if(b)return a.replace(ya,"&amp;").replace(za,"&lt;").replace(Aa,"&gt;").replace(Ba,"&quot;");else{if(!Ca.test(a))return a;if(a.indexOf("&")!=-1)a=a.replace(ya,"&amp;");if(a.indexOf("<")!=-1)a=a.replace(za,"&lt;");if(a.indexOf(">")!=-1)a=a.replace(Aa,"&gt;");if(a.indexOf('"')!=-1)a=a.replace(Ba,"&quot;");return a}}var ya=/&/g,za=/</g,Aa=/>/g,Ba=/\"/g,Ca=/[&<>\"]/;
function Da(a,b){for(var c=0,d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=String(b).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=Math.max(d.length,e.length),h=0;c==0&&h<f;h++){var i=d[h]||"",k=e[h]||"",l=RegExp("(\\d*)(\\D*)","g"),r=RegExp("(\\d*)(\\D*)","g");do{var n=l.exec(i)||["","",""],m=r.exec(k)||["","",""];if(n[0].length==0&&m[0].length==0)break;c=Ea(n[1].length==0?0:parseInt(n[1],10),m[1].length==0?0:parseInt(m[1],10))||Ea(n[2].length==0,m[2].length==0)||Ea(n[2],m[2])}while(c==
0)}return c}function Ea(a,b){if(a<b)return-1;else if(a>b)return 1;return 0}var Fa=ma();var u,Ga,Ha,Ia,Ja;function Ka(){return j.navigator?j.navigator.userAgent:null}Ja=Ia=Ha=Ga=u=false;var La;if(La=Ka()){var Ma=j.navigator;u=La.indexOf("Opera")==0;Ga=!u&&La.indexOf("MSIE")!=-1;Ia=(Ha=!u&&La.indexOf("WebKit")!=-1)&&La.indexOf("Mobile")!=-1;Ja=!u&&!Ha&&Ma.product=="Gecko"}var Na=u,v=Ga,Oa=Ja,w=Ha,Pa=Ia,Qa=j.navigator,Ra=(Qa&&Qa.platform||"").indexOf("Mac")!=-1,Sa,Ta="",Ua;
if(Na&&j.opera){var Va=j.opera.version;Ta=typeof Va=="function"?Va():Va}else{if(Oa)Ua=/rv\:([^\);]+)(\)|;)/;else if(v)Ua=/MSIE\s+([^\);]+)(\)|;)/;else if(w)Ua=/WebKit\/(\S+)/;if(Ua){var Wa=Ua.exec(Ka());Ta=Wa?Wa[1]:""}}Sa=Ta;var Xa={};function x(a){return Xa[a]||(Xa[a]=Da(Sa,a)>=0)};function Ya(a,b){ta(b,function(c,d){if(d=="style")a.style.cssText=c;else if(d=="class")a.className=c;else if(d=="for")a.htmlFor=c;else if(d in Za)a.setAttribute(Za[d],c);else a[d]=c})}var Za={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",type:"type"};
function $a(a,b){var c=b[0],d=b[1];if(v&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',xa(d.name),'"');if(d.type){c.push(' type="',xa(d.type),'"');d=ka(d);delete d.type}c.push(">");c=c.join("")}var e=a.createElement(c);if(d)if(o(d))e.className=d;else Ya(e,d);if(b.length>2){d=function(h){if(h)e.appendChild(o(h)?a.createTextNode(h):h)};for(c=2;c<b.length;c++){var f=b[c];ea(f)&&!(ga(f)&&f.nodeType>0)?oa(ab(f)?ra(f):f,d):d(f)}}return e}
function bb(a){for(var b;b=a.firstChild;)a.removeChild(b)}function ab(a){if(a&&typeof a.length=="number")if(ga(a))return typeof a.item=="function"||typeof a.item=="string";else if(fa(a))return typeof a.item=="function";return false}function cb(a){this.L=a||j.document||document}g=cb.prototype;g.a=function(a){return o(a)?this.L.getElementById(a):a};g.q=function(){return $a(this.L,arguments)};g.createElement=function(a){return this.L.createElement(a)};g.createTextNode=function(a){return this.L.createTextNode(a)};
g.appendChild=function(a,b){a.appendChild(b)};function y(a){return a*Math.PI/180};function A(){this.e=[];this.c=[];this.u=[]}A.prototype.T=null;A.prototype.h=null;A.prototype.Q=true;var B=[];B[0]=2;B[1]=2;B[2]=6;B[3]=6;B[4]=0;g=A.prototype;g.clear=function(){this.e.length=0;this.c.length=0;this.u.length=0;delete this.T;delete this.h;delete this.Q;return this};g.moveTo=function(a,b){if(this.e[this.e.length-1]==0)this.u.length-=2;else{this.e.push(0);this.c.push(1)}this.u.push(a,b);this.h=this.T=[a,b];return this};
g.lineTo=function(){var a=this.e[this.e.length-1];if(a==null)throw Error("Path cannot start with lineTo");if(a!=1){this.e.push(1);this.c.push(0)}for(a=0;a<arguments.length;a+=2){var b=arguments[a],c=arguments[a+1];this.u.push(b,c)}this.c[this.c.length-1]+=a/2;this.h=[b,c];return this};
g.Ma=function(){var a=this.e[this.e.length-1];if(a==null)throw Error("Path cannot start with curve");if(a!=2){this.e.push(2);this.c.push(0)}for(a=0;a<arguments.length;a+=6){var b=arguments[a+4],c=arguments[a+5];this.u.push(arguments[a],arguments[a+1],arguments[a+2],arguments[a+3],b,c)}this.c[this.c.length-1]+=a/6;this.h=[b,c];return this};g.close=function(){var a=this.e[this.e.length-1];if(a==null)throw Error("Path cannot start with close");if(a!=4){this.e.push(4);this.c.push(1);this.h=this.T}return this};
g.arc=function(a,b,c,d,e,f,h){a=a+c*Math.cos(y(e));b=b+d*Math.sin(y(e));if(h){if(!this.h||a!=this.h[0]||b!=this.h[1])this.lineTo(a,b)}else this.moveTo(a,b);return this.arcTo(c,d,e,f)};g.arcTo=function(a,b,c,d){var e=this.h[0]-a*Math.cos(y(c)),f=this.h[1]-b*Math.sin(y(c));e=e+a*Math.cos(y(c+d));f=f+b*Math.sin(y(c+d));this.e.push(3);this.c.push(1);this.u.push(a,b,c,d,e,f);this.Q=false;this.h=[e,f];return this};
g.bb=function(a,b,c,d){var e=this.h[0]-a*Math.cos(y(c)),f=this.h[1]-b*Math.sin(y(c)),h=y(d);d=Math.ceil(Math.abs(h)/Math.PI*2);h=h/d;c=y(c);for(var i=0;i<d;i++){var k=Math.cos(c),l=Math.sin(c),r=4/3*Math.sin(h/2)/(1+Math.cos(h/2)),n=e+(k-r*l)*a,m=f+(l+r*k)*b;c+=h;k=Math.cos(c);l=Math.sin(c);this.Ma(n,m,e+(k+r*l)*a,f+(l-r*k)*b,e+k*a,f+l*b)}return this};function db(a,b){for(var c=a.u,d=0,e=0,f=a.e.length;e<f;e++){var h=a.e[e],i=B[h]*a.c[e];b(h,c.slice(d,d+i));d+=i}}
g.S=function(){var a=new this.constructor;a.e=this.e.concat();a.c=this.c.concat();a.u=this.u.concat();a.T=this.T&&this.T.concat();a.h=this.h&&this.h.concat();a.Q=this.Q;return a};var C={};C[0]=A.prototype.moveTo;C[1]=A.prototype.lineTo;C[4]=A.prototype.close;C[2]=A.prototype.Ma;C[3]=A.prototype.bb;function eb(a){if(a.Q)return a.S();var b=new A;db(a,function(c,d){C[c].apply(b,d)});return b};function fb(a,b,c){if(b instanceof t){c=b.height;b=b.width}else{if(c==undefined)throw Error("missing height argument");c=c}a.style.width=typeof b=="number"?Math.round(b)+"px":b;a.style.height=typeof c=="number"?Math.round(c)+"px":c}
function D(a){var b=Na&&!x("10"),c;a:{c=a.nodeType==9?a:a.ownerDocument||a.document;if(c.defaultView&&c.defaultView.getComputedStyle)if(c=c.defaultView.getComputedStyle(a,"")){c=c.display;break a}c=null}if((c||(a.currentStyle?a.currentStyle.display:null)||a.style.display)!="none")return b?new t(a.offsetWidth||a.clientWidth,a.offsetHeight||a.clientHeight):new t(a.offsetWidth,a.offsetHeight);c=a.style;var d=c.display,e=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";c.display=
"inline";if(b){b=a.offsetWidth||a.clientWidth;a=a.offsetHeight||a.clientHeight}else{b=a.offsetWidth;a=a.offsetHeight}c.display=d;c.position=f;c.visibility=e;return new t(b,a)};function E(){}E.prototype.Ra=false;E.prototype.K=function(){if(!this.Ra){this.Ra=true;this.d()}};E.prototype.d=function(){};function F(a,b){this.type=a;this.currentTarget=this.target=b}q(F,E);F.prototype.d=function(){delete this.type;delete this.target;delete this.currentTarget};F.prototype.Y=false;F.prototype.sa=true;function G(a,b){a&&this.fa(a,b)}q(G,F);g=G.prototype;g.target=null;g.relatedTarget=null;g.offsetX=0;g.offsetY=0;g.clientX=0;g.clientY=0;g.screenX=0;g.screenY=0;g.button=0;g.keyCode=0;g.charCode=0;g.ctrlKey=false;g.altKey=false;g.shiftKey=false;g.metaKey=false;g.za=null;
g.fa=function(a,b){var c=this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(Oa)try{d=d.nodeName&&d}catch(e){d=null}}else if(c=="mouseover")d=a.fromElement;else if(c=="mouseout")d=a.toElement;this.relatedTarget=d;this.offsetX=a.offsetX!==undefined?a.offsetX:a.layerX;this.offsetY=a.offsetY!==undefined?a.offsetY:a.layerY;this.clientX=a.clientX!==undefined?a.clientX:a.pageX;this.clientY=a.clientY!==undefined?a.clientY:a.pageY;this.screenX=a.screenX||
0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(c=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.za=a;delete this.sa;delete this.Y};v&&x("8");G.prototype.d=function(){G.g.d.call(this);this.relatedTarget=this.currentTarget=this.target=this.za=null};function gb(){}var hb=0;g=gb.prototype;g.key=0;g.Z=false;g.La=false;g.fa=function(a,b,c,d,e,f){if(fa(a))this.Ua=true;else if(a&&a.handleEvent&&fa(a.handleEvent))this.Ua=false;else throw Error("Invalid listener argument");this.W=a;this.Ya=b;this.src=c;this.type=d;this.capture=!!e;this.ma=f;this.La=false;this.key=++hb;this.Z=false};g.handleEvent=function(a){if(this.Ua)return this.W.call(this.ma||this.src,a);return this.W.handleEvent.call(this.W,a)};function H(a,b){this.Va=b;this.N=[];if(a>this.Va)throw Error("[goog.structs.SimplePool] Initial cannot be greater than max");for(var c=0;c<a;c++)this.N.push(this.v?this.v():{})}q(H,E);H.prototype.v=null;H.prototype.Qa=null;function I(a){if(a.N.length)return a.N.pop();return a.v?a.v():{}}function J(a,b){a.N.length<a.Va?a.N.push(b):ib(a,b)}function ib(a,b){if(a.Qa)a.Qa(b);else if(fa(b.K))b.K();else for(var c in b)delete b[c]}
H.prototype.d=function(){H.g.d.call(this);for(var a=this.N;a.length;)ib(this,a.pop());delete this.N};var jb;var kb=(jb="ScriptEngine"in j&&j.ScriptEngine()=="JScript")?j.ScriptEngineMajorVersion()+"."+j.ScriptEngineMinorVersion()+"."+j.ScriptEngineBuildVersion():"0";var lb,mb,nb,ob,pb,qb,rb,sb,tb,ub,vb;
(function(){function a(){return{c:0,o:0}}function b(){return[]}function c(){function m(z){return h.call(m.src,m.key,z)}return m}function d(){return new gb}function e(){return new G}var f=jb&&!(Da(kb,"5.7")>=0),h;qb=function(m){h=m};if(f){lb=function(){return I(i)};mb=function(m){J(i,m)};nb=function(){return I(k)};ob=function(m){J(k,m)};pb=function(){return I(l)};rb=function(){J(l,c())};sb=function(){return I(r)};tb=function(m){J(r,m)};ub=function(){return I(n)};vb=function(m){J(n,m)};var i=new H(0,
600);i.v=a;var k=new H(0,600);k.v=b;var l=new H(0,600);l.v=c;var r=new H(0,600);r.v=d;var n=new H(0,600);n.v=e}else{lb=a;mb=ba;nb=b;ob=ba;pb=c;rb=ba;sb=d;tb=ba;ub=e;vb=ba}})();var K={},L={},M={},wb={};
function N(a,b,c,d,e){if(b)if(da(b)){for(var f=0;f<b.length;f++)N(a,b[f],c,d,e);return null}else{d=!!d;var h=L;b in h||(h[b]=lb());h=h[b];if(!(d in h)){h[d]=lb();h.c++}h=h[d];var i=ha(a),k;h.o++;if(h[i]){k=h[i];for(f=0;f<k.length;f++){h=k[f];if(h.W==c&&h.ma==e){if(h.Z)break;return k[f].key}}}else{k=h[i]=nb();h.c++}f=pb();f.src=a;h=sb();h.fa(c,f,a,b,d,e);c=h.key;f.key=c;k.push(h);K[c]=h;M[i]||(M[i]=nb());M[i].push(h);if(a.addEventListener){if(a==j||!a.va)a.addEventListener(b,f,d)}else a.attachEvent(xb(b),
f);return c}else throw Error("Invalid event type");}function yb(a,b,c,d,e){if(da(b)){for(var f=0;f<b.length;f++)yb(a,b[f],c,d,e);return null}d=!!d;a=zb(a,b,d);if(!a)return false;for(f=0;f<a.length;f++)if(a[f].W==c&&a[f].capture==d&&a[f].ma==e)return O(a[f].key);return false}
function O(a){if(!K[a])return false;var b=K[a];if(b.Z)return false;var c=b.src,d=b.type,e=b.Ya,f=b.capture;if(c.removeEventListener){if(c==j||!c.va)c.removeEventListener(d,e,f)}else c.detachEvent&&c.detachEvent(xb(d),e);c=ha(c);e=L[d][f][c];if(M[c]){var h=M[c];pa(h,b);h.length==0&&delete M[c]}b.Z=true;e.Wa=true;Ab(d,f,c,e);delete K[a];return true}
function Ab(a,b,c,d){if(!d.qa)if(d.Wa){for(var e=0,f=0;e<d.length;e++)if(d[e].Z){var h=d[e].Ya;h.src=null;rb(h);tb(d[e])}else{if(e!=f)d[f]=d[e];f++}d.length=f;d.Wa=false;if(f==0){ob(d);delete L[a][b][c];L[a][b].c--;if(L[a][b].c==0){mb(L[a][b]);delete L[a][b];L[a].c--}if(L[a].c==0){mb(L[a]);delete L[a]}}}}
function Bb(a,b,c){var d=0,e=a==null,f=b==null,h=c==null;c=!!c;if(e)ta(M,function(k){for(var l=k.length-1;l>=0;l--){var r=k[l];if((f||b==r.type)&&(h||c==r.capture)){O(r.key);d++}}});else{a=ha(a);if(M[a]){a=M[a];for(e=a.length-1;e>=0;e--){var i=a[e];if((f||b==i.type)&&(h||c==i.capture)){O(i.key);d++}}}}return d}function zb(a,b,c){var d=L;if(b in d){d=d[b];if(c in d){d=d[c];a=ha(a);if(d[a])return d[a]}}return null}function xb(a){if(a in wb)return wb[a];return wb[a]="on"+a}
function Cb(a,b,c,d,e){var f=1;b=ha(b);if(a[b]){a.o--;a=a[b];if(a.qa)a.qa++;else a.qa=1;try{for(var h=a.length,i=0;i<h;i++){var k=a[i];if(k&&!k.Z)f&=Db(k,e)!==false}}finally{a.qa--;Ab(c,d,b,a)}}return Boolean(f)}function Db(a,b){var c=a.handleEvent(b);a.La&&O(a.key);return c}
qb(function(a,b){if(!K[a])return true;var c=K[a],d=c.type,e=L;if(!(d in e))return true;e=e[d];var f,h;if(v){var i;if(!(i=b))a:{i="window.event".split(".");for(var k=j;f=i.shift();)if(k[f])k=k[f];else{i=null;break a}i=k}f=i;i=true in e;k=false in e;if(i){if(f.keyCode<0||f.returnValue!=undefined)return true;a:{var l=false;if(f.keyCode==0)try{f.keyCode=-1;break a}catch(r){l=true}if(l||f.returnValue==undefined)f.returnValue=true}}l=ub();l.fa(f,this);f=true;try{if(i){for(var n=nb(),m=l.currentTarget;m;m=
m.parentNode)n.push(m);h=e[true];h.o=h.c;for(var z=n.length-1;!l.Y&&z>=0&&h.o;z--){l.currentTarget=n[z];f&=Cb(h,n[z],d,true,l)}if(k){h=e[false];h.o=h.c;for(z=0;!l.Y&&z<n.length&&h.o;z++){l.currentTarget=n[z];f&=Cb(h,n[z],d,false,l)}}}else f=Db(c,l)}finally{if(n){n.length=0;ob(n)}l.K();vb(l)}return f}d=new G(b,this);try{f=Db(c,d)}finally{d.K()}return f});function P(a){this.O=a}q(P,E);var Eb=new H(0,100);function Fb(a,b,c,d,e,f){if(da(c))for(var h=0;h<c.length;h++)Fb(a,b,c[h],d,e,f);else{b=N(b,c,d||a,e||false,f||a.O||a);if(a.k)a.k[b]=true;else if(a.F){a.k=I(Eb);a.k[a.F]=true;a.F=null;a.k[b]=true}else a.F=b}return a}
function Gb(a,b,c,d,e,f){if(a.F||a.k)if(da(c))for(var h=0;h<c.length;h++)Gb(a,b,c[h],d,e,f);else{a:{d=d||a;f=f||a.O||a;e=!!(e||false);if(b=zb(b,c,e))for(c=0;c<b.length;c++)if(b[c].W==d&&b[c].capture==e&&b[c].ma==f){b=b[c];break a}b=null}if(b){b=b.key;O(b);if(a.k)ua(a.k,b);else if(a.F==b)a.F=null}}return a}function Hb(a){if(a.k){for(var b in a.k){O(b);delete a.k[b]}J(Eb,a.k);a.k=null}else a.F&&O(a.F)}P.prototype.d=function(){P.g.d.call(this);Hb(this)};
P.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function Q(){}q(Q,E);g=Q.prototype;g.va=true;g.ra=null;g.Ha=function(a){this.ra=a};g.addEventListener=function(a,b,c,d){N(this,a,b,c,d)};g.removeEventListener=function(a,b,c,d){yb(this,a,b,c,d)};
g.dispatchEvent=function(a){a=a;if(o(a))a=new F(a,this);else if(a instanceof F)a.target=a.target||this;else{var b=a;a=new F(a.type,this);wa(a,b)}b=1;var c,d=a.type,e=L;if(d in e){e=e[d];d=true in e;var f;if(d){c=[];for(f=this;f;f=f.ra)c.push(f);f=e[true];f.o=f.c;for(var h=c.length-1;!a.Y&&h>=0&&f.o;h--){a.currentTarget=c[h];b&=Cb(f,c[h],a.type,true,a)&&a.sa!=false}}if(false in e){f=e[false];f.o=f.c;if(d)for(h=0;!a.Y&&h<c.length&&f.o;h++){a.currentTarget=c[h];b&=Cb(f,c[h],a.type,false,a)&&a.sa!=false}else for(c=
this;!a.Y&&c&&f.o;c=c.ra){a.currentTarget=c;b&=Cb(f,c,a.type,false,a)&&a.sa!=false}}a=Boolean(b)}else a=true;return a};g.d=function(){Q.g.d.call(this);Bb(this);this.ra=null};function Ib(){}(function(a){a.Sa=function(){return a.kb||(a.kb=new a)}})(Ib);Ib.prototype.nb=0;Ib.Sa();function R(a){this.r=a||sa||(sa=new cb);this.pb=Jb}q(R,Q);R.prototype.jb=Ib.Sa();var Jb=null;g=R.prototype;g.P=null;g.r=null;g.j=false;g.b=null;g.pb=null;g.mb=null;g.X=null;g.i=null;g.ka=null;g.ub=false;g.a=aa("b");g.Ha=function(a){if(this.X&&this.X!=a)throw Error("Method not supported");R.g.Ha.call(this,a)};g.q=function(){this.b=this.r.createElement("div")};g.D=function(){this.j=true;this.i&&oa(this.i,function(a){!a.j&&a.a()&&a.D()},void 0)};
g.da=function(){this.i&&oa(this.i,function(a){a.j&&a.da()},void 0);this.la&&Hb(this.la);this.j=false};g.d=function(){R.g.d.call(this);this.j&&this.da();if(this.la){this.la.K();delete this.la}this.i&&oa(this.i,function(a){a.K()},void 0);!this.ub&&this.b&&this.b&&this.b.parentNode&&this.b.parentNode.removeChild(this.b);this.X=this.mb=this.b=this.ka=this.i=null};
g.removeChild=function(a,b){if(a){var c=o(a)?a:a.P||(a.P=":"+(a.jb.nb++).toString(36)),d;if(this.ka&&c){d=this.ka;d=c in d?d[c]:void 0;d=d||null}else d=null;a=d;if(c&&a){ua(this.ka,c);pa(this.i,a);if(b){a.da();a.b&&a.b&&a.b.parentNode&&a.b.parentNode.removeChild(a.b)}c=a;if(c==null)throw Error("Unable to set parent component");c.X=null;R.g.Ha.call(c,null)}}if(!a)throw Error("Child is not in parent component");return a};function S(a,b,c,d,e){R.call(this,e);this.width=a;this.height=b;this.m=c||null;this.ca=d||null}q(S,R);S.prototype.f=null;S.prototype.C=0;S.prototype.J=0;S.prototype.n=function(){if(this.j)return D(this.a());if(p(this.width)&&p(this.height))return new t(this.width,this.height);return null};function Kb(a){var b=a.n();return b?b.width/(a.m?new t(a.m,a.ca):a.n()).width:0};function Lb(a,b,c,d,e,f){if(arguments.length==6)this.setTransform(a,b,c,d,e,f);else if(arguments.length!=0)throw Error("Insufficient matrix parameters");else{this.z=this.B=1;this.t=this.A=this.G=this.H=0}}g=Lb.prototype;g.S=function(){return new Lb(this.z,this.t,this.A,this.B,this.G,this.H)};g.setTransform=function(a,b,c,d,e,f){if(!p(a)||!p(b)||!p(c)||!p(d)||!p(e)||!p(f))throw Error("Invalid transform parameters");this.z=a;this.t=b;this.A=c;this.B=d;this.G=e;this.H=f;return this};
g.scale=function(a,b){this.z*=a;this.t*=a;this.A*=b;this.B*=b;return this};g.translate=function(a,b){this.G+=a*this.z+b*this.A;this.H+=a*this.t+b*this.B;return this};g.rotate=function(a,b,c){var d=new Lb,e=Math.cos(a);a=Math.sin(a);b=d.setTransform(e,a,-a,e,b-b*e+c*a,c-b*a-c*e);c=this.z;d=this.A;this.z=b.z*c+b.t*d;this.A=b.A*c+b.B*d;this.G+=b.G*c+b.H*d;c=this.t;d=this.B;this.t=b.z*c+b.t*d;this.B=b.A*c+b.B*d;this.H+=b.G*c+b.H*d;return this};
g.toString=function(){return"matrix("+[this.z,this.t,this.A,this.B,this.G,this.H].join(",")+")"};function T(a,b){this.b=a;this.w=b;this.va=false}q(T,Q);g=T.prototype;g.w=null;g.b=null;g.ab=null;g.a=aa("b");g.addEventListener=function(a,b,c,d){N(this.b,a,b,c,d)};g.removeEventListener=function(a,b,c,d){yb(this.b,a,b,c,d)};g.d=function(){T.g.d.call(this);Bb(this.b)};function U(a,b,c,d){T.call(this,a,b);this.Ia=c;this.w.Ga(this,c);this.Aa=d;this.w.Fa(this,d)}q(U,T);U.prototype.Aa=null;U.prototype.Ia=null;U.prototype.eb=aa("Aa");U.prototype.fb=aa("Ia");function Mb(a,b,c,d){U.call(this,a,b,c,d)}q(Mb,U);function Nb(a,b){T.call(this,a,b)}q(Nb,T);function Ob(a,b){T.call(this,a,b)}q(Ob,T);function Pb(a,b,c,d){U.call(this,a,b,c,d)}q(Pb,U);function Qb(a,b,c,d){U.call(this,a,b,c,d)}q(Qb,U);function Rb(a){T.call(this,null,a);this.i=[]}q(Rb,Nb);Rb.prototype.clear=function(){if(this.i.length){this.i.length=0;V(this.w)}};Rb.prototype.appendChild=function(a){this.i.push(a)};Rb.prototype.s=function(){for(var a=0,b=this.i.length;a<b;a++)Sb(this.w,this.i[a])};function Tb(a,b,c,d,e,f,h,i){U.call(this,a,b,h,i);this.Na=c;this.Oa=d;this.qb=e;this.rb=f;this.I=new A;Ub(this);this.Xa=new Vb(null,b,this.I,h,i)}q(Tb,Mb);
function Ub(a){a.I.clear();a.I.arc(a.Na,a.Oa,a.qb,a.rb,0,360,false);a.I.close()}Tb.prototype.Ea=function(a,b){this.Na=a;this.Oa=b;Ub(this);var c=this.Xa,d=this.I;c.I=d.Q?d:eb(d);c.M&&V(c.w)};Tb.prototype.s=function(a){this.Xa.s(a)};function Wb(a,b,c,d,e,f,h,i){U.call(this,a,b,h,i);this.$=c;this.aa=d;this.ja=e;this.ea=f}q(Wb,Qb);Wb.prototype.M=false;
Wb.prototype.s=function(a){this.M=true;a.beginPath();a.moveTo(this.$,this.aa);a.lineTo(this.$,this.aa+this.ea);a.lineTo(this.$+this.ja,this.aa+this.ea);a.lineTo(this.$+this.ja,this.aa);a.closePath()};function Vb(a,b,c,d,e){U.call(this,a,b,d,e);this.I=c.Q?c:eb(c);this.M&&V(this.w)}q(Vb,Pb);Vb.prototype.M=false;
Vb.prototype.s=function(a){this.M=true;a.beginPath();db(this.I,function(b,c){switch(b){case 0:a.moveTo(c[0],c[1]);break;case 1:for(var d=0;d<c.length;d+=2)a.lineTo(c[d],c[d+1]);break;case 2:for(d=0;d<c.length;d+=6)a.bezierCurveTo(c[d],c[d+1],c[d+2],c[d+3],c[d+4],c[d+5]);break;case 3:throw Error("Canvas paths cannot contain arcs");case 4:a.closePath();break}})};function Xb(a,b,c,d,e,f,h){T.call(this,a,b);this.$=c;this.aa=d;this.ja=e;this.ea=f;this.sb=h}q(Xb,Ob);Xb.prototype.M=false;
Xb.prototype.s=function(a){if(this.Ta){this.ja&&this.ea&&a.drawImage(this.Ta,this.$,this.aa,this.ja,this.ea);this.M=true}else{a=new Image;a.onload=la(this.gb,this,a);a.src=this.sb}};Xb.prototype.gb=function(a){this.Ta=a;V(this.w)};function Yb(){};function W(a,b){this.p=a;this.ha=b||1}q(W,Yb);function Zb(a,b){this.Ka=a;this.p=b};function $b(a,b,c,d,e){S.call(this,a,b,c,d,e)}q($b,S);g=$b.prototype;g.Fa=function(){V(this)};g.Ga=function(){V(this)};function ac(a,b){var c=a.getContext();c.save();var d=b.ab?b.ab.S():new Lb,e=d.G,f=d.H;if(e||f)c.translate(e,f);(d=d.t)&&c.rotate(Math.asin(d))}g.q=function(){var a=this.r.q("div",{style:"position:relative;overflow:hidden"});this.b=a;this.ba=this.r.q("canvas");a.appendChild(this.ba);this.lb=this.f=new Rb(this);this.ob=0;bc(this)};
g.getContext=function(){this.a()||this.q();if(!this.U){this.U=this.ba.getContext("2d");this.U.save()}return this.U};g.n=function(){var a=this.width,b=this.height,c=o(a)&&a.indexOf("%")!=-1,d=o(b)&&b.indexOf("%")!=-1;if(!this.j&&(c||d))return null;var e,f;if(c){e=this.a().parentNode;f=D(e);a=parseFloat(a)*f.width/100}if(d){e=e||this.a().parentNode;f=f||D(e);b=parseFloat(b)*f.height/100}return new t(a,b)};
function bc(a){fb(a.a(),a.width,a.height);var b=a.n();if(b){fb(a.ba,b.width,b.height);a.ba.width=b.width;a.ba.height=b.height;a.U=null}}g.reset=function(){var a=this.getContext();a.restore();var b=this.n();b.width&&b.height&&a.clearRect(0,0,b.width,b.height);a.save()};g.clear=function(){this.reset();this.f.clear();for(var a=this.a();a.childNodes.length>1;)a.removeChild(a.lastChild)};
function V(a){if(a.Cb)a.Bb=true;else if(a.j){a.reset();if(a.m){var b=a.n();a.getContext().scale(b.width/a.m,b.height/a.ca)}if(a.C||a.J)a.getContext().translate(-a.C,-a.J);ac(a,a.f);a.f.s(a.U);a.getContext().restore()}}
function Sb(a,b){var c=a.getContext();ac(a,b);if(!b.eb||!b.fb)b.s(c);else{var d=b.Aa;if(d)if(d instanceof W){if(d.ha!=0){c.globalAlpha=d.ha;c.fillStyle=d.p;b.s(c);c.fill();c.globalAlpha=1}}else{var e=c.createLinearGradient(d.xb(),d.zb(),d.yb(),d.Ab());e.addColorStop(0,d.vb());e.addColorStop(1,d.wb());c.fillStyle=e;b.s(c);c.fill()}if(d=b.Ia){b.s(c);c.strokeStyle=d.p;d=d.Ka;if(o(d)&&d.indexOf("px")!=-1)d=parseFloat(d)/Kb(a);c.lineWidth=d;c.stroke()}}a.getContext().restore()}
g.l=function(a,b){b=b||this.f;b.appendChild(a);this.j&&!this.ob&&!(b!=this.f&&b!=this.lb)&&Sb(this,a)};g.xa=function(a,b,c,d,e,f,h){a=new Tb(null,this,a,b,c,d,e,f);this.l(a,h);return a};g.ya=function(a,b,c,d,e,f,h){a=new Wb(null,this,a,b,c,d,e,f);this.l(a,h);return a};g.drawImage=function(a,b,c,d,e,f){a=new Xb(null,this,a,b,c,d,e);this.l(a,f);return a};g.d=function(){this.U=null;$b.g.d.call(this)};g.D=function(){var a=this.n();$b.g.D.call(this);if(!a){bc(this);this.dispatchEvent("resize")}V(this)};function cc(a,b){this.na=a||1;this.ia=b||dc;this.ua=la(this.tb,this);this.Da=ma()}q(cc,Q);cc.prototype.enabled=false;var dc=j.window;g=cc.prototype;g.R=null;g.tb=function(){if(this.enabled){var a=ma()-this.Da;if(a>0&&a<this.na*0.8)this.R=this.ia.setTimeout(this.ua,this.na-a);else{this.dispatchEvent(ec);if(this.enabled){this.R=this.ia.setTimeout(this.ua,this.na);this.Da=ma()}}}};g.start=function(){this.enabled=true;if(!this.R){this.R=this.ia.setTimeout(this.ua,this.na);this.Da=ma()}};
g.stop=function(){this.enabled=false;if(this.R){this.ia.clearTimeout(this.R);this.R=null}};g.d=function(){cc.g.d.call(this);this.stop();delete this.ia};var ec="tick";function fc(a,b){T.call(this,a,b)}q(fc,Nb);fc.prototype.clear=function(){bb(this.a())};function gc(a,b,c,d){U.call(this,a,b,c,d)}q(gc,Mb);gc.prototype.Ea=function(a,b){var c=this.a(),d={cx:a,cy:b};for(var e in d)c.setAttribute(e,d[e])};function hc(a,b,c,d){U.call(this,a,b,c,d)}q(hc,Qb);function ic(a,b){T.call(this,a,b)}q(ic,Ob);function jc(a,b,c,d,e){S.call(this,a,b,c,d,e);this.Pa={};this.Ja=w&&!x(526);this.O=new P(this)}var kc;q(jc,S);function lc(a,b,c){a=a.r.L.createElementNS("http://www.w3.org/2000/svg",b);if(c)for(var d in c)a.setAttribute(d,c[d]);return a}g=jc.prototype;g.l=function(a,b){(b||this.f).a().appendChild(a.a())};g.Fa=function(a,b){var c=a.a();if(b instanceof W){c.setAttribute("fill",b.p);c.setAttribute("fill-opacity",b.ha)}else c.setAttribute("fill","none")};
g.Ga=function(a,b){var c=a.a();if(b){c.setAttribute("stroke",b.p);var d=b.Ka;o(d)&&d.indexOf("px")!=-1?c.setAttribute("stroke-width",parseFloat(d)/Kb(this)):c.setAttribute("stroke-width",d)}else c.setAttribute("stroke","none")};
g.q=function(){var a=lc(this,"svg",{width:this.width,height:this.height,overflow:"hidden"}),b=lc(this,"g");this.wa=lc(this,"defs");this.f=new fc(b,this);a.appendChild(this.wa);a.appendChild(b);this.b=a;if(this.m||this.C||this.J){this.a().setAttribute("preserveAspectRatio","none");this.Ja?this.ta():this.a().setAttribute("viewBox",this.C+" "+this.J+" "+(this.m?this.m+" "+this.ca:""))}};
g.ta=function(){if(this.j&&(this.m||this.C||!this.J)){var a=this.n();if(a.width==0)this.a().style.visibility="hidden";else{this.a().style.visibility="";var b=-this.C,c=-this.J,d=a.width/this.m;a=a.height/this.ca;this.f.a().setAttribute("transform","scale("+d+" "+a+") translate("+b+" "+c+")")}}};
g.n=function(){if(!Oa)return D(this.a());var a=this.width,b=this.height,c=o(a)&&a.indexOf("%")!=-1,d=o(b)&&b.indexOf("%")!=-1;if(!this.j&&(c||d))return null;var e,f;if(c){e=this.a().parentNode;f=D(e);a=parseFloat(a)*f.width/100}if(d){e=e||this.a().parentNode;f=f||D(e);b=parseFloat(b)*f.height/100}return new t(a,b)};g.clear=function(){this.f.clear();bb(this.wa);this.Pa={}};g.xa=function(a,b,c,d,e,f,h){a=lc(this,"ellipse",{cx:a,cy:b,rx:c,ry:d});e=new gc(a,this,e,f);this.l(e,h);return e};
g.ya=function(a,b,c,d,e,f,h){a=lc(this,"rect",{x:a,y:b,width:c,height:d});e=new hc(a,this,e,f);this.l(e,h);return e};g.drawImage=function(a,b,c,d,e,f){a=lc(this,"image",{x:a,y:b,width:c,height:d,"image-rendering":"optimizeQuality",preserveAspectRatio:"none"});a.setAttributeNS("http://www.w3.org/1999/xlink","href",e);e=new ic(a,this);this.l(e,f);return e};
g.D=function(){var a=this.n();jc.g.D.call(this);a||this.dispatchEvent("resize");if(this.Ja){a=this.width;var b=this.height;typeof a=="string"&&a.indexOf("%")!=-1&&typeof b=="string"&&b.indexOf("%")!=-1&&Fb(this.O,mc(),ec,this.ta);this.ta()}};g.da=function(){jc.g.da.call(this);this.Ja&&Gb(this.O,mc(),ec,this.ta)};g.d=function(){delete this.Pa;delete this.wa;delete this.f;jc.g.d.call(this)};function mc(){if(!kc){kc=new cc(400);kc.start()}return kc};function nc(){return this.b=this.w.r.a(this.P)||this.b}function oc(a,b){this.P=a.id;T.call(this,a,b)}q(oc,Nb);oc.prototype.a=nc;oc.prototype.clear=function(){bb(this.a())};function pc(a,b,c,d,e,f,h,i){this.P=a.id;U.call(this,a,b,h,i);this.cb=c;this.db=d;this.Za=e;this.$a=f}q(pc,Mb);pc.prototype.a=nc;pc.prototype.Ea=function(a,b){this.cb=a;this.db=b;qc(this.a(),a-this.Za,b-this.$a,this.Za*2,this.$a*2)};function rc(a,b,c,d){this.P=a.id;U.call(this,a,b,c,d)}q(rc,Qb);rc.prototype.a=nc;
function sc(a,b){this.P=a.id;T.call(this,a,b)}q(sc,Ob);sc.prototype.a=nc;function X(a,b,c,d,e){S.call(this,a,b,c,d,e);this.O=new P(this)}q(X,S);var tc=document.documentMode&&document.documentMode>=8;function uc(a){var b;if(b=o(a)){b=a.length-1;b=b>=0&&a.lastIndexOf("%",b)==b}return b?a:parseFloat(a.toString())+"px"}function Y(a){return Math.round(parseFloat(a.toString())*100)}function vc(a,b){var c=a.r.createElement("g_vml_:"+b);c.id="goog_"+Fa++;return c}function wc(a){if(tc&&a.j)a.a().innerHTML=a.a().innerHTML}
X.prototype.l=function(a,b){(b||this.f).a().appendChild(a.a());wc(this)};X.prototype.Fa=function(a,b){var c=a.a();c.fillcolor="";for(var d=0;d<c.childNodes.length;d++){var e=c.childNodes[d];e.tagName=="fill"&&c.removeChild(e)}if(b instanceof W)if(b.p=="transparent")c.filled=false;else if(b.ha!=1){c.filled=true;d=vc(this,"fill");d.opacity=Math.round(b.ha*100)+"%";d.color=b.p;c.appendChild(d)}else{c.filled=true;c.fillcolor=b.p}else c.filled=false;wc(this)};
X.prototype.Ga=function(a,b){var c=a.a();if(b){c.stroked=true;var d=b.Ka;d=o(d)&&d.indexOf("px")==-1?parseFloat(d):d*Kb(this);var e=c.getElementsByTagName("stroke")[0];if(d<1){e=e||vc(this,"stroke");e.opacity=d;e.Db="1px";e.color=b.p;c.appendChild(e)}else{e&&c.removeChild(e);c.strokecolor=b.p;c.strokeweight=d+"px"}}else c.stroked=false;wc(this)};
function qc(a,b,c,d,e){var f=a.style;f.position="absolute";f.left=Math.round((parseFloat(b.toString())-0.5)*100)+"px";f.top=Math.round((parseFloat(c.toString())-0.5)*100)+"px";f.width=Y(d)+"px";f.height=Y(e)+"px";if(a.tagName=="shape")a.coordsize=Y(d)+" "+Y(e)}try{eval("document.namespaces")}catch(xc){}g=X.prototype;
g.q=function(){var a=this.r.L;if(!a.namespaces.g_vml_){tc?a.namespaces.add("g_vml_","urn:schemas-microsoft-com:vml","#default#VML"):a.namespaces.add("g_vml_","urn:schemas-microsoft-com:vml");a.createStyleSheet().cssText="g_vml_\\:*{behavior:url(#default#VML)}"}a=this.width;var b=this.height,c=this.r.q("div",{style:"overflow:hidden;position:relative;width:"+uc(a)+";height:"+uc(b)});this.b=c;var d=vc(this,"group"),e=d.style;e.position="absolute";e.left=e.top=0;e.width=this.width;e.height=this.height;
d.coordsize=this.m?Y(this.m)+" "+Y(this.ca):Y(a)+" "+Y(b);d.coordorigin=this.C!==undefined?Y(this.C)+" "+Y(this.J):"0 0";c.appendChild(d);this.f=new oc(d,this);N(c,"resize",la(this.Ba,this))};g.Ba=function(){var a=D(this.a()),b=this.f.a().style;if(a.width){b.width=a.width+"px";b.height=a.height+"px"}else{for(a=this.a();a&&a.currentStyle&&a.currentStyle.display!="none";)a=a.parentNode;a&&a.currentStyle&&Fb(this.O,a,"propertychange",this.Ba)}this.dispatchEvent("resize")};
g.n=function(){var a=this.a();return new t(a.style.pixelWidth||a.offsetWidth||1,a.style.pixelHeight||a.offsetHeight||1)};g.clear=function(){this.f.clear()};g.xa=function(a,b,c,d,e,f,h){var i=vc(this,"oval");qc(i,a-c,b-d,c*2,d*2);a=new pc(i,this,a,b,c,d,e,f);this.l(a,h);return a};g.ya=function(a,b,c,d,e,f,h){var i=vc(this,"rect");qc(i,a,b,c,d);a=new rc(i,this,e,f);this.l(a,h);return a};
g.drawImage=function(a,b,c,d,e,f){var h=vc(this,"image");qc(h,a,b,c,d);if(tc)h.src=e;else h.setAttribute("src",e);a=new sc(h,this);this.l(a,f);return a};g.D=function(){X.g.D.call(this);this.Ba();wc(this)};g.d=function(){this.f=null;X.g.d.call(this)};function yc(a,b,c,d,e){if(!v&&!(w&&x("525")))return true;if(Ra&&e)return zc(a);if(e&&!d)return false;if(v&&!c&&(b==17||b==18))return false;if(v&&d&&b==a)return false;switch(a){case 13:return true;case 27:return!w}return zc(a)}
function zc(a){if(a>=48&&a<=57)return true;if(a>=96&&a<=106)return true;if(a>=65&&a<=90)return true;switch(a){case 32:case 63:case 107:case 109:case 110:case 111:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return true;default:return false}};function Ac(a){if(a){this.pa&&this.detach();this.b=a;this.oa=N(this.b,"keypress",this);this.Ca=N(this.b,"keydown",this.hb,false,this);this.pa=N(this.b,"keyup",this.ib,false,this)}}q(Ac,Q);g=Ac.prototype;g.b=null;g.oa=null;g.Ca=null;g.pa=null;g.ga=-1;g.V=-1;
var Bc={"3":13,"12":144,"63232":38,"63233":40,"63234":37,"63235":39,"63236":112,"63237":113,"63238":114,"63239":115,"63240":116,"63241":117,"63242":118,"63243":119,"63244":120,"63245":121,"63246":122,"63247":123,"63248":44,"63272":46,"63273":36,"63275":35,"63276":33,"63277":34,"63289":144,"63302":45},Cc={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},Dc={61:187,
59:186},Ec=v||w&&x("525");g=Ac.prototype;g.hb=function(a){if(Ec&&!yc(a.keyCode,this.ga,a.shiftKey,a.ctrlKey,a.altKey))this.handleEvent(a);else this.V=Oa&&a.keyCode in Dc?Dc[a.keyCode]:a.keyCode};g.ib=function(){this.V=this.ga=-1};
g.handleEvent=function(a){var b=a.za,c,d;if(v&&a.type=="keypress"){c=this.V;d=c!=13&&c!=27?b.keyCode:0}else if(w&&a.type=="keypress"){c=this.V;d=b.charCode>=0&&b.charCode<63232&&zc(c)?b.charCode:0}else if(Na){c=this.V;d=zc(c)?b.keyCode:0}else{c=b.keyCode||this.V;d=b.charCode||0;if(Ra&&d==63&&!c)c=191}var e=c,f=b.keyIdentifier;if(c)if(c>=63232&&c in Bc)e=Bc[c];else{if(c==25&&a.shiftKey)e=9}else if(f&&f in Cc)e=Cc[f];a=e==this.ga;this.ga=e;b=new Fc(e,d,a,b);try{this.dispatchEvent(b)}finally{b.K()}};
g.a=aa("b");g.detach=function(){if(this.oa){O(this.oa);O(this.Ca);O(this.pa);this.pa=this.Ca=this.oa=null}this.b=null;this.ga=-1};g.d=function(){Ac.g.d.call(this);this.detach()};function Fc(a,b,c,d){d&&this.fa(d,void 0);this.type="key";this.keyCode=a;this.charCode=b;this.repeat=c}q(Fc,G);var Z;Z=v?new X(1400,850,void 0,void 0,void 0):w&&(!x("420")||Pa)?new $b(1400,850,void 0,void 0,void 0):new jc(1400,850,void 0,void 0,void 0);Z.q();for(var Gc=new W("yellow"),Hc=new Zb(2,"green"),Ic=new W("blue"),Jc=new Zb(1,"black"),$={x:1,y:1},Kc=0;Kc<30;Kc++)for(var Lc=0;Lc<20;Lc++)Z.ya(5+Kc*40,5+Lc*40,35,35,Hc,Gc);$.graphic=Z.xa(5+$.x*40+17.5,5+$.y*40+17.5,8.75,8.75,Jc,Ic);redraw_dot=function(){$.graphic.Ea(5+$.x*40+17.5,5+$.y*40+17.5)};var Mc=new Ac(document);
N(Mc,"key",function(a){if(a.keyCode==38&&$.y>0)$.y-=1;else if(a.keyCode==39&&$.x<=28)$.x+=1;else if(a.keyCode==40&&$.y<=18)$.y+=1;else if(a.keyCode==37&&$.x>0)$.x-=1;redraw_dot()});var Nc=document.getElementById("shapes");if(Z.j)throw Error("Component already rendered");Z.b||Z.q();Nc?Nc.insertBefore(Z.b,null):Z.r.L.body.appendChild(Z.b);if(!Z.X||Z.X.j)Z.D();

