application: gps-maps
version: 1
runtime: python
api_version: 1
default_expiration: "1d"
#default_expiration: "60s"

handlers:

- url: /e5299a3f17ebbcce23d7a8c9.html
  static_files: e5299a3f17ebbcce23d7a8c9.html
  upload: e5299a3f17ebbcce23d7a8c9.html

- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /svg
  static_dir: svg
  mime_type: image/svg+xml

- url: /images/(.*\.(gif|png|jpg|ico))
  static_files: images/\1
  upload: images/(.*\.(gif|png|jpg|ico))

- url: .*/(.*\.(gif|png|jpg|ico))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg|ico))

- url: /static
  static_dir: static
#  static_files: static/\1
#  upload: static/.*

- url: /flatcgi
  script: flatcgi.py

- url: /admin/.*
  script: admin.py
  login: required
#  login: admin
#- url: /a
#  script: gps-maps.py

- url: /layout.html
  static_files: layout.html
  upload: layout.html

- url: /chat
  script: chat_wsh.py

- url: /pyamftry
  script: pyamftry.py

- url: /chatpage
  script: chat_wsh.py

- url: /crossdomain.xml
  static_files: crossdomain.xml
  upload: crossdomain.xml

- url: /test.html
  static_files: test.html
  upload: test.html

- url: /test.swf
  static_files: test.swf
  upload: test.swf

- url: /testqueue.*
  script: testqueue.py

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /track.*
  script: track.py

- url: /commet.*
  script: commet.py

- url: /admin.*
  script: gps-admin.py
  login: admin

- url: /bingps.*
  script: gps-bingps.py

- url: /carsico/.*
  script: gps-carsico.py

- url: /benchmark.*
  script: benchmark.py

- url: /.*
  script: gps-maps.py

admin_console:
  pages:
  - name: Appstats
    url: /stats

derived_file_type:
- python_precompiled

builtins:
- datastore_admin: on

#skip_files:
#- ^(.*/)?app\.yaml
#- ^(.*/)?app\.yml
#- ^(.*/)?index\.yaml
#- ^(.*/)?index\.yml
#- ^(.*/)?#.*#
#- ^(.*/)?.*~
#- ^(.*/)?.*\.py[co]
#- ^(.*/)?.*/RCS/.*
#- ^(.*/)?\..*
#- ^(.*/)?utils/.*
#- ^(.*/)?\js/ideas/.*
#- ^(.*/)?\.settings/.*
#- ^(.*/)?\.svn/.*

#error_handlers:
#  - file: default_error.html
#
#  - error_code: over_quota
#    file: over_quota.html
